'use strict';

/**
 * Builds the plain-text and HTML bodies for a service failure report email.
 * Images are referenced by Content-ID (cid) so they render inline; the same
 * files are also attached to the message.
 */

function esc(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function orDash(v) {
  const s = (v == null ? '' : String(v)).trim();
  return s === '' ? '—' : s;
}

function fmtDateTime(iso) {
  if (!iso) return '—';
  const d = new Date(iso.includes('T') || iso.includes(' ') ? iso.replace(' ', 'T') + (iso.endsWith('Z') ? '' : 'Z') : iso);
  if (isNaN(d)) return String(iso);
  return d.toISOString().replace('T', ' ').replace(/\.\d+Z$/, ' UTC');
}

function buildSubject(report) {
  if (report.email_subject && report.email_subject.trim()) return report.email_subject.trim();
  const parts = ['Service Failure Report', orDash(report.symptom_title)];
  if (report.product && report.product.trim()) parts.push(report.product.trim());
  return parts.filter((p) => p && p !== '—').join(' – ');
}

function buildText(report, team, images) {
  const L = [];
  L.push('SERVICE / FAILURE REPORT');
  L.push('Reference: ' + report.public_id);
  L.push('');
  L.push('== SYMPTOM DETAILS ==');
  L.push('Symptom Title        : ' + orDash(report.symptom_title));
  L.push('Symptom Description  : ' + orDash(report.symptom_description));
  L.push('Symptom Category     : ' + orDash(report.symptom_category));
  L.push('Product / System     : ' + orDash(report.product));
  L.push('Affected Units       : ' + (report.affected_units_list.length
    ? report.affected_units_list.join(' | ') : '—'));
  L.push('Initial Response Date: ' + orDash(report.initial_response_date));
  L.push('Emergency Response Action (ERA):');
  L.push('  ' + orDash(report.era).split('\n').join('\n  '));
  L.push('ERA Date             : ' + orDash(report.era_date));
  L.push('Contained in 24 Hrs  : ' + orDash(report.contained_24h));
  L.push('');
  L.push('== TEAM (D1) ==');
  if (team.length) {
    L.push('Member | Role | Mobile | Email | Remarks');
    L.push('-------------------------------------------------------------');
    team.forEach((m) => {
      L.push([orDash(m.member_name), orDash(m.role), orDash(m.mobile), orDash(m.email), orDash(m.remarks)].join(' | '));
    });
  } else {
    L.push('(no team members listed)');
  }
  L.push('');
  L.push('== PROBLEM DESCRIPTION (D2) ==');
  L.push('Problem Description:');
  L.push('  ' + orDash(report.problem_description).split('\n').join('\n  '));
  L.push('Failure Mode:');
  L.push('  ' + orDash(report.failure_mode).split('\n').join('\n  '));
  L.push('');
  L.push('== RECORD ==');
  L.push('Entered By          : ' + orDash(report.entered_by));
  L.push('Updated By          : ' + orDash(report.updated_by));
  L.push('Report Created Date : ' + fmtDateTime(report.created_at));
  L.push('Last Updated Date   : ' + fmtDateTime(report.updated_at));
  L.push('');
  L.push('== PROBLEM IMAGES / FAILURE EVIDENCE ==');
  if (images.length) {
    images.forEach((img, i) => {
      L.push(`${i + 1}. ${orDash(img.caption)}  [${img.original_name || img.filename}]`);
    });
    L.push('(images attached to this email)');
  } else {
    L.push('(no images attached)');
  }
  L.push('');
  L.push('— Generated by the EnergySYS Service Report tool —');
  return L.join('\n');
}

function buildHtml(report, team, images) {
  const C = {
    ink: '#04361F', green: '#00A24C', greenLink: '#00753A', orange: '#F26A1B',
    steel: '#5E6B62', line: '#D7E0D9', bg: '#FBFBF8', mist: '#EAF1EC',
  };
  const wrap = (inner) => `
  <div style="background:${C.bg};padding:24px 0;font-family:Arial,Helvetica,sans-serif;color:${C.ink};">
    <table role="presentation" width="640" cellpadding="0" cellspacing="0" style="margin:0 auto;width:640px;max-width:100%;background:#fff;border:1px solid ${C.line};border-radius:6px;overflow:hidden;">
      <tr><td style="background:${C.ink};padding:18px 24px;">
        <span style="color:#fff;font-size:18px;font-weight:bold;letter-spacing:.02em;">EnergySYS</span>
        <span style="color:#8FB3A1;font-size:12px;"> &nbsp;·&nbsp; Service / Failure Report</span>
      </td></tr>
      <tr><td style="height:3px;background:${C.orange};font-size:0;line-height:0;">&nbsp;</td></tr>
      <tr><td style="padding:24px;">${inner}</td></tr>
      <tr><td style="padding:14px 24px;background:${C.mist};border-top:1px solid ${C.line};color:${C.steel};font-size:11px;">
        Reference ${esc(report.public_id)} &nbsp;·&nbsp; generated ${esc(fmtDateTime(new Date().toISOString()))}
      </td></tr>
    </table>
  </div>`;

  const h2 = (t) => `<h2 style="margin:26px 0 10px;font-size:14px;letter-spacing:.06em;text-transform:uppercase;color:${C.greenLink};border-bottom:1px solid ${C.line};padding-bottom:6px;">${esc(t)}</h2>`;
  const row = (k, v) => `<tr>
      <td style="padding:6px 12px 6px 0;vertical-align:top;color:${C.steel};font-size:13px;white-space:nowrap;">${esc(k)}</td>
      <td style="padding:6px 0;vertical-align:top;font-size:13px;color:${C.ink};">${v}</td>
    </tr>`;
  const multiline = (v) => esc(orDash(v)).replace(/\n/g, '<br>');

  let s = '';
  s += `<p style="margin:0 0 4px;font-size:20px;font-weight:bold;">${esc(orDash(report.symptom_title))}</p>`;
  s += `<p style="margin:0;color:${C.steel};font-size:13px;">${esc(orDash(report.product))} &nbsp;·&nbsp; ${esc(orDash(report.symptom_category))} &nbsp;·&nbsp; status: <strong style="color:${report.status === 'sent' ? C.green : C.orange};">${esc(report.status)}</strong></p>`;

  s += h2('1. Symptom Details');
  s += `<table role="presentation" cellpadding="0" cellspacing="0" width="100%">`;
  s += row('Symptom Title', esc(orDash(report.symptom_title)));
  s += row('Symptom Description', multiline(report.symptom_description));
  s += row('Symptom Category', esc(orDash(report.symptom_category)));
  s += row('Product / System', esc(orDash(report.product)));
  s += row('Affected Units / Failure', report.affected_units_list.length
    ? report.affected_units_list.map((u) => esc(u)).join('<br>') : '—');
  s += row('Initial Response Date', esc(orDash(report.initial_response_date)));
  s += row('Emergency Response Action', multiline(report.era));
  s += row('ERA Date', esc(orDash(report.era_date)));
  s += row('Contained in 24 Hrs', esc(orDash(report.contained_24h)));
  s += `</table>`;

  s += h2('2. Team (D1)');
  if (team.length) {
    s += `<table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;font-size:12px;">
      <tr style="background:${C.mist};">
        <th align="left" style="padding:7px 8px;border:1px solid ${C.line};">Member</th>
        <th align="left" style="padding:7px 8px;border:1px solid ${C.line};">Role</th>
        <th align="left" style="padding:7px 8px;border:1px solid ${C.line};">Mobile</th>
        <th align="left" style="padding:7px 8px;border:1px solid ${C.line};">Email</th>
        <th align="left" style="padding:7px 8px;border:1px solid ${C.line};">Remarks</th>
      </tr>`;
    team.forEach((m) => {
      s += `<tr>
        <td style="padding:7px 8px;border:1px solid ${C.line};">${esc(orDash(m.member_name))}</td>
        <td style="padding:7px 8px;border:1px solid ${C.line};">${esc(orDash(m.role))}</td>
        <td style="padding:7px 8px;border:1px solid ${C.line};">${esc(orDash(m.mobile))}</td>
        <td style="padding:7px 8px;border:1px solid ${C.line};">${esc(orDash(m.email))}</td>
        <td style="padding:7px 8px;border:1px solid ${C.line};">${esc(orDash(m.remarks))}</td>
      </tr>`;
    });
    s += `</table>`;
  } else {
    s += `<p style="font-size:13px;color:${C.steel};">No team members listed.</p>`;
  }

  s += h2('3. Problem Description (D2)');
  s += `<table role="presentation" cellpadding="0" cellspacing="0" width="100%">`;
  s += row('Problem Description', multiline(report.problem_description));
  s += row('Failure Mode', multiline(report.failure_mode));
  s += `</table>`;

  s += h2('4. Problem Images / Failure Evidence');
  if (images.length) {
    s += `<table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr>`;
    images.forEach((img, i) => {
      if (i > 0 && i % 2 === 0) s += `</tr><tr>`;
      s += `<td width="50%" style="padding:6px;vertical-align:top;">
        <img src="cid:${esc(img.cid)}" alt="${esc(orDash(img.caption))}" style="width:100%;border:1px solid ${C.line};border-radius:4px;display:block;">
        <div style="font-size:12px;color:${C.steel};padding:6px 2px;">${esc(orDash(img.caption))} <span style="color:#9AA;">— ${esc(img.original_name || img.filename)}</span></div>
      </td>`;
    });
    if (images.length % 2 === 1) s += `<td width="50%">&nbsp;</td>`;
    s += `</tr></table>`;
  } else {
    s += `<p style="font-size:13px;color:${C.steel};">No images attached.</p>`;
  }

  s += h2('Record');
  s += `<table role="presentation" cellpadding="0" cellspacing="0" width="100%">`;
  s += row('Entered By', esc(orDash(report.entered_by)));
  s += row('Updated By', esc(orDash(report.updated_by)));
  s += row('Report Created Date', esc(fmtDateTime(report.created_at)));
  s += row('Last Updated Date', esc(fmtDateTime(report.updated_at)));
  s += `</table>`;

  return wrap(s);
}

/* ---- Website enquiry (contact form) ---------------------------------- */

function buildEnquiryText(d, publicId) {
  const L = [];
  L.push('NEW CUSTOMER QUERY');
  L.push('');
  L.push('Name:');
  L.push(orDash(d.name));
  L.push('');
  L.push('Company:');
  L.push(orDash(d.company));
  L.push('');
  L.push('Email:');
  L.push(orDash(d.email));
  L.push('');
  L.push('Mobile:');
  L.push(orDash(d.phone));
  L.push('');
  L.push('Query Type:');
  L.push(orDash(d.query_type));
  L.push('');
  L.push('Subject:');
  L.push(orDash(d.subject));
  L.push('');
  L.push('Message:');
  L.push(String(d.message || '').trim());
  if (d.attachment_original) {
    L.push('');
    L.push('Attachment:');
    L.push(d.attachment_original + ' (attached to this email)');
  }
  L.push('');
  L.push('==============================');
  L.push('Submitted from the website.');
  L.push('Reference ' + publicId + '  ·  ' + fmtDateTime(new Date().toISOString()));
  return L.join('\n');
}

function buildEnquiryHtml(d, publicId) {
  const C = { ink: '#04361F', green: '#00A24C', greenLink: '#00753A', orange: '#F26A1B',
    steel: '#5E6B62', line: '#D7E0D9', bg: '#FBFBF8', mist: '#EAF1EC' };
  const row = (k, v) => `<tr>
      <td style="padding:6px 12px 6px 0;color:${C.steel};font-size:13px;white-space:nowrap;vertical-align:top;">${esc(k)}</td>
      <td style="padding:6px 0;font-size:13px;color:${C.ink};vertical-align:top;">${v}</td>
    </tr>`;
  let s = '';
  s += `<p style="margin:0 0 4px;font-size:20px;font-weight:bold;">${esc(orDash(d.subject))}</p>`;
  s += `<p style="margin:0;color:${C.steel};font-size:13px;">Reference ${esc(publicId)} · ${esc(fmtDateTime(new Date().toISOString()))}</p>`;
  s += `<h2 style="margin:24px 0 10px;font-size:14px;letter-spacing:.06em;text-transform:uppercase;color:${C.greenLink};border-bottom:1px solid ${C.line};padding-bottom:6px;">Contact</h2>`;
  s += `<table role="presentation" cellpadding="0" cellspacing="0" width="100%">`;
  s += row('Name', esc(orDash(d.name)));
  s += row('Company', esc(orDash(d.company)));
  s += row('Email', `<a href="mailto:${esc(d.email)}" style="color:${C.greenLink};">${esc(orDash(d.email))}</a>`);
  s += row('Mobile', esc(orDash(d.phone)));
  s += row('Query Type', esc(orDash(d.query_type)));
  if (d.ref) s += row('Part ref', esc(d.ref));
  if (d.attachment_original) s += row('Attachment', esc(d.attachment_original) + ' <span style="color:#9AA;">(attached)</span>');
  if (d.page) s += row('From page', esc(d.page));
  s += `</table>`;
  s += `<h2 style="margin:24px 0 10px;font-size:14px;letter-spacing:.06em;text-transform:uppercase;color:${C.greenLink};border-bottom:1px solid ${C.line};padding-bottom:6px;">Message</h2>`;
  s += `<div style="font-size:14px;color:${C.ink};white-space:pre-wrap;line-height:1.6;">${esc(d.message)}</div>`;
  s += `<p style="margin-top:22px;color:${C.steel};font-size:12px;">Reply to this email to respond directly to ${esc(orDash(d.name))}. &nbsp;Submitted from the website.</p>`;

  return `<div style="background:${C.bg};padding:24px 0;font-family:Arial,Helvetica,sans-serif;color:${C.ink};">
    <table role="presentation" width="620" cellpadding="0" cellspacing="0" style="margin:0 auto;width:620px;max-width:100%;background:#fff;border:1px solid ${C.line};border-radius:6px;overflow:hidden;">
      <tr><td style="background:${C.ink};padding:16px 22px;"><span style="color:#fff;font-size:17px;font-weight:bold;">EnergySYS</span><span style="color:#8FB3A1;font-size:12px;"> &nbsp;·&nbsp; Website enquiry</span></td></tr>
      <tr><td style="height:3px;background:${C.orange};font-size:0;line-height:0;">&nbsp;</td></tr>
      <tr><td style="padding:22px;">${s}</td></tr>
    </table>
  </div>`;
}

/* ===================================================================
   WIND FARM SERVICE REQUEST  (POST /api/service-request)
   =================================================================== */

function buildServiceRequestSubject(d) {
  const farm = (d.farm_name || '').trim() || 'Wind farm';
  const pr = (d.priority || '').trim();
  return 'New Wind Farm Service Request – ' + farm + (pr ? ' [' + pr + ']' : '');
}

function buildServiceRequestText(d, publicId, files) {
  const L = [];
  const kv = (k, v) => { L.push(k + ':'); L.push(orDash(v)); L.push(''); };
  L.push('NEW WIND FARM SERVICE REQUEST');
  L.push('');
  L.push('-- Customer --');
  kv('Full Name', d.full_name);
  kv('Company', d.company);
  kv('Email', d.email);
  kv('Phone', d.phone);
  kv('Country', d.country);
  kv('City / Location', d.city);
  L.push('-- Wind Farm --');
  kv('Wind Farm Name', d.farm_name);
  kv('Wind Farm Location', d.farm_location);
  kv('Number of Turbines', d.turbine_count);
  kv('Turbine Manufacturer / OEM', d.turbine_oem);
  kv('Turbine Model', d.turbine_model);
  kv('Turbine Capacity (MW)', d.turbine_capacity_mw);
  kv('Total Wind Farm Capacity (MW)', d.farm_capacity_mw);
  kv('Commissioning Year', d.commissioning_year);
  L.push('-- Service Required --');
  L.push(d.services ? String(d.services).split('\n').map((x) => '  - ' + x).join('\n') : '  —');
  L.push('');
  L.push('-- Service Request Details --');
  L.push('Problem / Service Description:');
  L.push(String(d.description || '').trim());
  L.push('');
  kv('Number of Turbines Affected', d.turbines_affected);
  kv('Turbine ID(s)', d.turbine_ids);
  kv('Current Turbine Status', d.turbine_status);
  kv('Required Service Date', d.required_date);
  kv('Priority', d.priority);
  if (String(d.comments || '').trim()) {
    L.push('-- Additional Information --');
    L.push(String(d.comments).trim());
    L.push('');
  }
  if (files && files.length) {
    L.push('-- Uploaded Documents --');
    files.forEach((f) => {
      L.push('  - ' + f.original_name + ' (' + Math.max(1, Math.round(f.size / 1024)) + ' KB)' +
        (f.attached ? ' — attached' : ' — stored on server (too large to attach)'));
    });
    L.push('');
  }
  L.push('==============================');
  L.push('Submitted from the website service-request page.');
  L.push('Reference ' + publicId + '  ·  ' + fmtDateTime(new Date().toISOString()));
  return L.join('\n');
}

function buildServiceRequestHtml(d, publicId, files) {
  const C = { ink: '#04361F', green: '#00A24C', greenLink: '#00753A', orange: '#F26A1B',
    steel: '#5E6B62', line: '#D7E0D9', bg: '#FBFBF8', mist: '#EAF1EC' };
  const row = (k, v) => `<tr>
      <td style="padding:6px 12px 6px 0;color:${C.steel};font-size:13px;white-space:nowrap;vertical-align:top;">${esc(k)}</td>
      <td style="padding:6px 0;font-size:13px;color:${C.ink};vertical-align:top;">${v == null || v === '' ? '&mdash;' : v}</td>
    </tr>`;
  const head = (t) => `<h2 style="margin:24px 0 10px;font-size:14px;letter-spacing:.06em;text-transform:uppercase;color:${C.greenLink};border-bottom:1px solid ${C.line};padding-bottom:6px;">${esc(t)}</h2>`;

  let s = '';
  s += `<p style="margin:0 0 4px;font-size:20px;font-weight:bold;">${esc(orDash(d.farm_name))}</p>`;
  s += `<p style="margin:0;color:${C.steel};font-size:13px;">Reference ${esc(publicId)} &middot; ${esc(fmtDateTime(new Date().toISOString()))}` +
       (d.priority ? ` &middot; <strong style="color:${d.priority === 'Emergency' ? C.orange : C.greenLink};">${esc(d.priority)}</strong>` : '') + `</p>`;

  s += head('Customer');
  s += `<table role="presentation" cellpadding="0" cellspacing="0" width="100%">`;
  s += row('Full Name', esc(d.full_name));
  s += row('Company', esc(d.company));
  s += row('Email', `<a href="mailto:${esc(d.email)}" style="color:${C.greenLink};">${esc(d.email)}</a>`);
  s += row('Phone', esc(d.phone));
  s += row('Country', esc(d.country));
  s += row('City / Location', esc(d.city));
  s += `</table>`;

  s += head('Wind Farm');
  s += `<table role="presentation" cellpadding="0" cellspacing="0" width="100%">`;
  s += row('Wind Farm Name', esc(d.farm_name));
  s += row('Wind Farm Location', esc(d.farm_location));
  s += row('Number of Turbines', esc(d.turbine_count));
  s += row('Turbine Manufacturer / OEM', esc(d.turbine_oem));
  s += row('Turbine Model', esc(d.turbine_model));
  s += row('Turbine Capacity (MW)', esc(d.turbine_capacity_mw));
  s += row('Total Wind Farm Capacity (MW)', esc(d.farm_capacity_mw));
  s += row('Commissioning Year', esc(d.commissioning_year));
  s += `</table>`;

  s += head('Service Required');
  if (d.services && String(d.services).trim()) {
    s += `<ul style="margin:0;padding-left:20px;font-size:13px;color:${C.ink};line-height:1.7;">` +
      String(d.services).split('\n').map((x) => `<li>${esc(x)}</li>`).join('') + `</ul>`;
  } else {
    s += `<p style="margin:0;font-size:13px;color:${C.steel};">&mdash;</p>`;
  }

  s += head('Service Request Details');
  s += `<div style="font-size:14px;color:${C.ink};white-space:pre-wrap;line-height:1.6;margin-bottom:10px;">${esc(d.description)}</div>`;
  s += `<table role="presentation" cellpadding="0" cellspacing="0" width="100%">`;
  s += row('Turbines Affected', esc(d.turbines_affected));
  s += row('Turbine ID(s)', esc(d.turbine_ids));
  s += row('Current Turbine Status', esc(d.turbine_status));
  s += row('Required Service Date', esc(d.required_date));
  s += row('Priority', esc(d.priority));
  s += `</table>`;

  if (String(d.comments || '').trim()) {
    s += head('Additional Information');
    s += `<div style="font-size:14px;color:${C.ink};white-space:pre-wrap;line-height:1.6;">${esc(d.comments)}</div>`;
  }

  if (files && files.length) {
    s += head('Uploaded Documents');
    s += `<ul style="margin:0;padding-left:20px;font-size:13px;color:${C.ink};line-height:1.7;">` +
      files.map((f) => `<li>${esc(f.original_name)} <span style="color:#9AA;">(${Math.max(1, Math.round(f.size / 1024))} KB${f.attached ? ', attached' : ', stored on server'})</span></li>`).join('') +
      `</ul>`;
  }

  s += `<p style="margin-top:22px;color:${C.steel};font-size:12px;">Reply to this email to respond directly to ${esc(orDash(d.full_name))}. &nbsp;Submitted from the website.</p>`;

  return `<div style="background:${C.bg};padding:24px 0;font-family:Arial,Helvetica,sans-serif;color:${C.ink};">
    <table role="presentation" width="620" cellpadding="0" cellspacing="0" style="margin:0 auto;width:620px;max-width:100%;background:#fff;border:1px solid ${C.line};border-radius:6px;overflow:hidden;">
      <tr><td style="background:${C.ink};padding:16px 22px;"><span style="color:#fff;font-size:17px;font-weight:bold;">EnergySYS</span><span style="color:#8FB3A1;font-size:12px;"> &nbsp;&middot;&nbsp; Wind farm service request</span></td></tr>
      <tr><td style="height:3px;background:${C.orange};font-size:0;line-height:0;">&nbsp;</td></tr>
      <tr><td style="padding:22px;">${s}</td></tr>
    </table>
  </div>`;
}

/* ===================================================================
   G8D WIND FARM SERVICE REQUEST  (POST /api/g8d/submit)
   =================================================================== */

function buildG8DSubject(data, publicId) {
  var farm = (data.d2 && data.d2.wind_farm_name) ? data.d2.wind_farm_name.trim() : '';
  var turbine = (data.d2 && data.d2.turbine_id) ? data.d2.turbine_id.trim() : '';
  return 'New G8D Service Request – ' + (farm || 'Wind farm') + (turbine ? ' / ' + turbine : '') + ' (' + publicId + ')';
}

function buildG8DNoteText(data, publicId, currentDiscipline) {
  var d1 = data.d1 || {}, d2 = data.d2 || {};
  var L = [];
  L.push('NEW G8D WIND FARM SERVICE REQUEST SUBMITTED');
  L.push('');
  L.push('Reference: ' + publicId);
  L.push('Current discipline: ' + currentDiscipline);
  L.push('Wind Farm: ' + orDash(d2.wind_farm_name) + (d2.turbine_id ? ' (Turbine ' + d2.turbine_id + ')' : ''));
  L.push('Submitted by: ' + orDash(d1.contact_person) + (d1.email ? ' <' + d1.email + '>' : '') + (d1.company_name ? ', ' + d1.company_name : ''));
  L.push('');
  L.push('Full details are in the attached G8D report (PDF).');
  L.push('');
  L.push('==============================');
  L.push('Submitted from the website G8D service-request page.');
  L.push('Reference ' + publicId + '  ·  ' + fmtDateTime(new Date().toISOString()));
  return L.join('\n');
}

function buildG8DNoteHtml(data, publicId, currentDiscipline) {
  var C = { ink: '#04361F', green: '#00A24C', greenLink: '#00753A', orange: '#F26A1B',
    steel: '#5E6B62', line: '#D7E0D9', bg: '#FBFBF8', mist: '#EAF1EC' };
  var d1 = data.d1 || {}, d2 = data.d2 || {};
  var row = function (k, v) {
    if (v == null || v === '') return '';
    return '<tr><td style="padding:5px 12px 5px 0;color:' + C.steel + ';font-size:12px;white-space:nowrap;vertical-align:top;">' + esc(k) +
      '</td><td style="padding:5px 0;font-size:12px;color:' + C.ink + ';vertical-align:top;">' + esc(String(v)) + '</td></tr>';
  };

  var s = '';
  s += '<p style="margin:0 0 4px;font-size:19px;font-weight:bold;">' + esc(orDash(d2.wind_farm_name)) + (d2.turbine_id ? ' — ' + esc(d2.turbine_id) : '') + '</p>';
  s += '<p style="margin:0;color:' + C.steel + ';font-size:12px;">Reference ' + esc(publicId) + ' &middot; ' + esc(fmtDateTime(new Date().toISOString())) +
    ' &middot; Current discipline <strong>' + esc(currentDiscipline) + '</strong></p>';
  s += '<table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="margin-top:18px;">' +
    row('Submitted By', d1.contact_person) + row('Email', d1.email) + row('Company', d1.company_name) + '</table>';
  s += '<p style="margin:20px 0 0;font-size:14px;color:' + C.ink + ';">The full G8D details (D1–D8) are in the attached PDF report.</p>';
  s += '<p style="margin-top:20px;color:' + C.steel + ';font-size:11px;">Reply to this email to respond directly to ' + esc(orDash(d1.contact_person)) + '.</p>';

  return '<div style="background:' + C.bg + ';padding:24px 0;font-family:Arial,Helvetica,sans-serif;color:' + C.ink + ';">' +
    '<table role="presentation" width="640" cellpadding="0" cellspacing="0" style="margin:0 auto;width:640px;max-width:100%;background:#fff;border:1px solid ' + C.line + ';border-radius:6px;overflow:hidden;">' +
    '<tr><td style="background:' + C.ink + ';padding:16px 22px;"><span style="color:#fff;font-size:17px;font-weight:bold;">EnergySYS</span><span style="color:#8FB3A1;font-size:12px;"> &nbsp;&middot;&nbsp; G8D wind farm service request</span></td></tr>' +
    '<tr><td style="height:3px;background:' + C.orange + ';font-size:0;line-height:0;">&nbsp;</td></tr>' +
    '<tr><td style="padding:22px;">' + s + '</td></tr>' +
    '</table></div>';
}

function buildG8DSenderSubject(data, publicId) {
  var farm = (data.d2 && data.d2.wind_farm_name) ? data.d2.wind_farm_name.trim() : '';
  return 'Your G8D Service Request' + (farm ? ' — ' + farm : '') + ' (' + publicId + ')';
}

function buildG8DSenderText(data, publicId) {
  var d1 = data.d1 || {}, d2 = data.d2 || {};
  var L = [];
  L.push('Hi ' + (d1.contact_person || 'there') + ',');
  L.push('');
  L.push('Thank you for submitting a G8D wind farm service request to EnergySYS.');
  L.push('A copy of your submitted report is attached to this email for your records.');
  L.push('');
  L.push('Reference: ' + publicId);
  L.push('Wind Farm: ' + orDash(d2.wind_farm_name) + (d2.turbine_id ? ' (Turbine ' + d2.turbine_id + ')' : ''));
  L.push('Submitted: ' + fmtDateTime(new Date().toISOString()));
  L.push('');
  L.push('Our team will review your request and follow up with you shortly.');
  L.push('');
  L.push('— EnergySYS');
  return L.join('\n');
}

function buildG8DSenderHtml(data, publicId) {
  var C = { ink: '#04361F', green: '#00A24C', greenLink: '#00753A', orange: '#F26A1B',
    steel: '#5E6B62', line: '#D7E0D9', bg: '#FBFBF8', mist: '#EAF1EC' };
  var d1 = data.d1 || {}, d2 = data.d2 || {};
  var s = '';
  s += '<p style="margin:0 0 14px;font-size:15px;">Hi ' + esc(d1.contact_person || 'there') + ',</p>';
  s += '<p style="margin:0 0 14px;font-size:14px;">Thank you for submitting a G8D wind farm service request to EnergySYS. ' +
    'A copy of your submitted report is attached to this email for your records.</p>';
  s += '<table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="margin:18px 0;background:' + C.mist + ';border-radius:6px;">' +
    '<tr><td style="padding:14px 16px;font-size:13px;color:' + C.ink + ';">' +
    '<div><strong>Reference:</strong> ' + esc(publicId) + '</div>' +
    '<div><strong>Wind Farm:</strong> ' + esc(orDash(d2.wind_farm_name)) + (d2.turbine_id ? ' (Turbine ' + esc(d2.turbine_id) + ')' : '') + '</div>' +
    '<div><strong>Submitted:</strong> ' + esc(fmtDateTime(new Date().toISOString())) + '</div>' +
    '</td></tr></table>';
  s += '<p style="margin:0;font-size:14px;color:' + C.ink + ';">Our team will review your request and follow up with you shortly.</p>';
  s += '<p style="margin-top:22px;font-size:14px;color:' + C.ink + ';">— EnergySYS</p>';

  return '<div style="background:' + C.bg + ';padding:24px 0;font-family:Arial,Helvetica,sans-serif;color:' + C.ink + ';">' +
    '<table role="presentation" width="640" cellpadding="0" cellspacing="0" style="margin:0 auto;width:640px;max-width:100%;background:#fff;border:1px solid ' + C.line + ';border-radius:6px;overflow:hidden;">' +
    '<tr><td style="background:' + C.ink + ';padding:16px 22px;"><span style="color:#fff;font-size:17px;font-weight:bold;">EnergySYS</span><span style="color:#8FB3A1;font-size:12px;"> &nbsp;&middot;&nbsp; Your G8D service request</span></td></tr>' +
    '<tr><td style="height:3px;background:' + C.orange + ';font-size:0;line-height:0;">&nbsp;</td></tr>' +
    '<tr><td style="padding:22px;">' + s + '</td></tr>' +
    '</table></div>';
}

module.exports = {
  buildSubject, buildText, buildHtml,
  buildEnquiryText, buildEnquiryHtml,
  buildServiceRequestSubject, buildServiceRequestText, buildServiceRequestHtml,
  buildG8DSubject, buildG8DNoteText, buildG8DNoteHtml,
  buildG8DSenderSubject, buildG8DSenderText, buildG8DSenderHtml,
};
